source 'https://github.com/jiaojiaozhe/XAbstractionLibrary-Specs'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'XAbstractionLibrary-NetWork_Example' do
  pod 'XAbstractionLibrary-NetWork', :path => '../'

  target 'XAbstractionLibrary-NetWork_Tests' do
    inherit! :search_paths

    
  end
end
